import {
  TRACK_TOP_SCALE,
  TRACK_BOTTOM_SCALE,
  TRACK_SHOULDER_SCALE,
  TRACK_CAR_SIZE_RELATIVE_TO_LANE,
  TRACK_CAR_LANE_CENTER_OFFSET,
  CAR_LANE_SCALE_ADJUSTMENT,
  NAMECARD_SCALE
} from '../../config'

export const BASE_HEIGHT = 800
export const LANE_COUNT = 5

// sizes
export const TRACK_HEIGHT = 1 - (TRACK_TOP_SCALE + TRACK_BOTTOM_SCALE)
export const SHOULDER_HEIGHT = (TRACK_HEIGHT * TRACK_SHOULDER_SCALE)
export const LANE_HEIGHT = (TRACK_HEIGHT - SHOULDER_HEIGHT) / LANE_COUNT
export const CAR_HEIGHT = LANE_HEIGHT * TRACK_CAR_SIZE_RELATIVE_TO_LANE
export const NAMECARD_HEIGHT = CAR_HEIGHT * NAMECARD_SCALE

// positions
export const TRACK_TOP = TRACK_TOP_SCALE
export const TRACK_BOTTOM = TRACK_TOP + TRACK_HEIGHT
export const TRACK_CENTER = (TRACK_TOP + TRACK_BOTTOM) / 2
export const LANE_START = TRACK_TOP + (SHOULDER_HEIGHT / 2)
export const LANE_CENTER = LANE_START + (LANE_HEIGHT / 2) - (CAR_HEIGHT * TRACK_CAR_LANE_CENTER_OFFSET)

// create the sizing for each lane
export const LANES = []
for (let i = 0; i < LANE_COUNT; i++) {
  // calculate the y positions for each lane
  const y = (i * LANE_HEIGHT) + LANE_CENTER
  LANES.push(y)
}

// calculated values
export const SCALED_CAR_HEIGHT = CAR_HEIGHT * BASE_HEIGHT * CAR_LANE_SCALE_ADJUSTMENT
export const SCALED_LANE_HEIGHT = LANE_HEIGHT * BASE_HEIGHT
export const SCALED_NAMECARD_HEIGHT = NAMECARD_HEIGHT * BASE_HEIGHT
